# Generated by Django 2.1.7 on 2019-05-05 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('S', 'Single user'), ('G', 'Group')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_groups', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat group',
            },
        ),
        migrations.AddField(
            model_name='call',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatMe.Group'),
        ),
        migrations.AddField(
            model_name='call',
            name='receivers',
            field=models.ManyToManyField(related_name='received_calls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='call',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_calls', to=settings.AUTH_USER_MODEL),
        ),
    ]
