# Generated by Django 2.1.7 on 2019-05-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatMe', '0003_call_missed_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
    ]
